### ISSUE TITLE
Is Gmail actually working?

### ISSUE THREAD

**Issue by markc** [r-a-y/bp-reply-by-email#65]
I just tried testing this plugin with Gmail and to the best of my knowledge I followed the simple instructions but I am getting a...
```
Error: Unable to connect to inbox - Can not authenticate to IMAP server: [AUTHENTICATIONFAILED] Invalid credentials (Failure)
```
I had previously set it up with my own mail server and was working but unfortunately my mail server does not understand the "+" tag separator so I thought I'd try Gmail just to get something to work... in other words my basic installation does work with sending emails in general. I also notice there was no option for TLS/SSL so unless there is some magic under the hood then that would explain why it's not working with Gmail. But surely some folks are using this plugin with Gmail?

**Comment by r-a-y** [comment]
See:
https://wordpress.org/support/topic/warning-imap_open-functionimap-open-couldnt-open-stream-popgmailcom9#post-4443925

Probably GMail flagging the login as suspicious.  Try logging into GMail / Google Accounts and whitelist the IP for the login attempt.

**Comment by markc** [comment]
Thanks for you reply. I tried a few more things with Gmail but no luck. The only whitelisting I could find was for incoming email addresses and alias, nothing for an IP. Anyway, when I went back to the settings I noticed "Address Tag Separator" (I didn't know what that meant the first time I saw the settings page) and changed it to a "-" and now it works with my mailserver (Courier-MTA). This is a really cool feature :-)

Related issue, I notice in the code there are some commented out sections about extending this functionality to WP blog posts and comments. Is that a real thing for the future?

**Comment by r-a-y** [comment]
> The only whitelisting I could find was for incoming email addresses and alias, nothing for an IP.

You might have to go to Google Accounts and not Gmail:
https://accounts.google.com

Then check your login history.  The IP used from your server to check RBE should be listed there.  Google might have temporarily banned logins from that IP because of suspicious activity.

> Anyway, when I went back to the settings I noticed "Address Tag Separator" (I didn't know what that meant the first time I saw the settings page) and changed it to a "-" and now it works with my mailserver (Courier-MTA). This is a really cool feature :-)

Yeah, that's the point of the address tag separator!  Glad you figured it out.  Also glad it works on non-Gmail email addresses.

> Related issue, I notice in the code there are some commented out sections about extending this functionality to WP blog posts and comments. Is that a real thing for the future?

It's commented out for a reason.

RBE isn't in the business of managing subscriptions for other content.  RBE is really a middleman to other mail plugins.  For instance, BuddyPress groups really only works because of the BP Group Email Subscription plugin.  At-mentions and private messaging are native BP features.

If I were to support blog posts and comments, it would be as another module for an existing WP email subscription plugin.

**Comment by r-a-y** [comment]
Going to close this since you appear to be up-and-running.
