### ISSUE TITLE
website provider email service

### ISSUE THREAD

**Issue by McCage** [r-a-y/bp-reply-by-email#95]
Hi, I would like to use this plug-in for my BP website. I would prefer to use my own website provider email service to make it working. Can somebody explain to me why this possibility is not presented and explained?
http://ruilkringdelftwestland.nl

**Comment by r-a-y** [comment]
If your email provider suppports IMAP, you could use IMAP mode, but I highly prefer Inbound.  If you use Inbound, you could use your website's email address (eg. `reply.ruilkringdelftwestland.nl`), but you have to look into configuring your DNS to use Inbound Mode.

Please read the [Starter Guide](https://github.com/r-a-y/bp-reply-by-email/wiki/Starter-Guide) and do further research into either Inbound Mode or IMAP Mode.

Since this isn't a bug report, I'm going to close this issue.
